 variables flipkart product price list
mobile_price=float(input("mobile price :"))
watch_price=float(input("watch price :"))
bike_price=int(input("bike price :"))
customer_name=input("Enter name :")
customer_age=input("Enter age :")
customer_mailid=input("Enter mailid :")
customer_address=input("Enter address :")
payment_creditcard=input(input("Enter cardnumber :"))
total = mobile_price + watch_price + bike_price
flipkart_url =input('https://www.flipkart.com/')
print(customer_name, customer_age, customer_address, customer_mailid)
print(payment_creditcard)
print(mobile_price + watch_price + bike_price)
print(flipkart_url)
print(type(mobile_price))
print(type(bike_price))
print(id(mobile_price))
print(id(watch_price))
print(id(bike_price))
print(customer_mailid.upper())
print(customer_mailid.title())
print(type(flipkart_url))
